---
- name: Prepare instances
  hosts: all
  gather_facts: false

  tasks:
    - name: "Prepare Rocky 8"
      when: inventory_hostname == "rocky-8"
      ansible.builtin.raw: dnf install -y python3.12
      changed_when: true
      become: true

    # - name: "Prepare Windows"
    #   when: inventory_hostname | lower is match("windows-.*")
    #   block:
    #     - name: Enable powershell as default shell on windows
    #       ansible.builtin.raw: powershell -Command \"New-ItemProperty -Path 'HKLM:\\SOFTWARE\\OpenSSH' -Name DefaultShell
    #         -Value 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' -PropertyType String -Force\"
    #       changed_when: false

    #     - name: Reset SSH connection after shell change
    #       ansible.builtin.meta: reset_connection

    #     - name: Wait for connection
    #       ansible.builtin.wait_for_connection:
    #         timeout: 120
