---
- name: Import GPG key
  ansible.builtin.rpm_key:
    key: "{{ sentinelone_client_gpgkey }}"
  become: true
  when: sentinelone_client_gpgkey

- name: Include digest tasks
  ansible.builtin.include_tasks: digest.yml

- name: Install package (digest)
  ansible.builtin.command: "rpm -ivh --nodigest /tmp/{{ sentinelone_client_filename | basename }}"
  register: rpmout
  changed_when:
    - "'Updating / installing' in rpmout.stdout"
  failed_when:
    - rpmout.failed
    - "'is already installed' not in rpmout.stderr"
  ignore_errors: true
  become: true
  when: sentinelone_client_digest is defined

- name: Install package
  ansible.builtin.yum:
    name: "/tmp/{{ sentinelone_client_filename | basename }}"
  become: true
  when: sentinelone_client_digest is not defined
