---
# defaults file for install_agent

# Mandatory variables
install_agent_console_url: "{{ console_url }}"
install_agent_api_token: "{{ api_token }}"
install_agent_site: "{{ site }}"

# Optional variables
install_agent_gpg_key: "{{ gpg_key }}"
install_agent_custom_version: "{{ custom_version | default(omit) }}"
install_agent_group: "{{ group | default(omit) }}"
install_agent_win_use_exe: "{{ win_use_exe | default(false) }}"
install_agent_win_allow_reboot: "{{ win_allow_reboot | default(true) }}"
install_agent_agent_version: "{{ agent_version | default('latest') }}"
install_agent_hide_sensitive: "{{ hide_sensitive | default(true) }}"
install_agent_lx_force_new_token: "{{ lx_force_new_token | default(false) }}"
install_agent_check_console_retries: "{{ check_console_retries | default(3) }}"
install_agent_check_console_retry_delay: "{{ check_console_retry_delay | default(20) }}"
install_agent_linux_custom_client_url: "{{ linux_custom_client_url | default('') }}"
