objects:
  role:
    install_agent:
      description: Entrypoint for install_agent role
      name: install_agent
      version_added: null
    sentinelone_client_legacy:
      description: Entrypoint for sentinelone_client_legacy role
      name: sentinelone_client_legacy
      version_added: 2.0.0
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    agent_info:
      description: Get info about the SentinelOne agent package
      name: agent_info
      namespace: ''
      version_added: 2.0.0
    config_overrides:
      description: Manage SentinelOne Config Overrides
      name: config_overrides
      namespace: ''
      version_added: 1.0.0
    download_agent:
      description: Download SentinelOne agent from Management Console
      name: download_agent
      namespace: ''
      version_added: 1.1.0
    filters:
      description: Manage SentinelOne Filters
      name: filters
      namespace: ''
      version_added: 1.0.0
    groups:
      description: Manage SentinelOne Groups
      name: groups
      namespace: ''
      version_added: 1.0.0
    path_exclusions:
      description: Manage SentinelOne Path Exclusions
      name: path_exclusions
      namespace: ''
      version_added: 1.0.0
    policies:
      description: Manage SentinelOne Policies
      name: policies
      namespace: ''
      version_added: 1.0.0
    sites:
      description: Manage SentinelOne Sites
      name: sites
      namespace: ''
      version_added: 1.0.0
    upgrade_policies:
      description: Manage SentinelOne Upgrade Policies
      name: upgrade_policies
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 2.1.0
