objects:
  role:
    install_agent:
      description: Entrypoint for install_agent role
      name: install_agent
      version_added: null
    sentinelone_client_legacy:
      description: Entrypoint for sentinelone_client_legacy role
      name: sentinelone_client_legacy
      version_added: 2.0.0
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    sentinelone_agent_info:
      description: Get info about the SentinelOne agent package
      name: sentinelone_agent_info
      namespace: ''
      version_added: 2.0.0
    sentinelone_config_overrides:
      description: Manage SentinelOne Config Overrides
      name: sentinelone_config_overrides
      namespace: ''
      version_added: 1.0.0
    sentinelone_download_agent:
      description: Download SentinelOne agent from Management Console
      name: sentinelone_download_agent
      namespace: ''
      version_added: 1.1.0
    sentinelone_filters:
      description: Manage SentinelOne Filters
      name: sentinelone_filters
      namespace: ''
      version_added: 1.0.0
    sentinelone_groups:
      description: Manage SentinelOne Groups
      name: sentinelone_groups
      namespace: ''
      version_added: 1.0.0
    sentinelone_path_exclusions:
      description: Manage SentinelOne Path Exclusions
      name: sentinelone_path_exclusions
      namespace: ''
      version_added: 1.0.0
    sentinelone_policies:
      description: Manage SentinelOne Policies
      name: sentinelone_policies
      namespace: ''
      version_added: 1.0.0
    sentinelone_sites:
      description: Manage SentinelOne Sites
      name: sentinelone_sites
      namespace: ''
      version_added: 1.0.0
    sentinelone_upgrade_policies:
      description: Manage SentinelOne Upgrade Policies
      name: sentinelone_upgrade_policies
      namespace: ''
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 2.0.2
