---
install_agent_remote_pkg_path: "{{ install_agent_tmp_dir }}{{ install_agent_return_download_agent.original_message.filename }}"
install_agent_remote_gpg_key_path: "/tmp/sentinel_one.gpg"
install_agent_signed_package: "{{ false if install_agent_agent_version == 'custom' and custom_version is version('23.3.2.12', '<') else true }}"
