---
- name: "Converge: Install agent on Linux"
  ansible.builtin.include_role:
    name: sva.sentinelone.install_agent
  vars:
    console_url: "{{ console_url }}"
    api_token: "{{ api_token }}"
    site: "{{ site }}"
    gpg_key: "{{ gpg_key_path | default(omit) }}"  # optional
  when: ansible_facts.ansible_system is defined and
    ansible_facts.ansible_system == "Linux"

- name: "Converge: Install agent on Windows"
  ansible.builtin.include_role:
    name: sva.sentinelone.install_agent
  vars:
    console_url: "{{ console_url }}"
    api_token: "{{ api_token }}"
    site: "{{ site }}"
    win_use_exe: false  # optional
    win_allow_reboot: true  # optional
  when: os_family == "Windows"
