---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Set SentinelONE client installation file (Debian)
      ansible.builtin.set_fact:
        file_sentinelone: sentinelone_latest.deb
      when: ansible_os_family == 'Debian'

    - name: Set SentinelONE client installation file (Red Hat)
      ansible.builtin.set_fact:
        file_sentinelone: sentinelone_latest.rpm
      when: ansible_os_family == 'RedHat'

    - name: Set SentinelONE client installation file (SUSE)
      ansible.builtin.set_fact:
        file_sentinelone: sentinelone_latest.rpm
      when: ansible_os_family == 'Suse'

  roles:
    - role: sva.sentinelone.sentinelone_client_legacy
      sentinelone_client_filename: "{{ file_sentinelone }}"
      # sentinelone_client_token: '...'
      # sentinelone_client_gpgkey: '...'
