---
- name: Gather RPM package version
  ansible.builtin.command:
    cmd: "rpm -qp --queryformat '%{VERSION}' {{ remote_pkg_path }}"
  register: sentinelone_client_rpm_version
  changed_when: false

- name: Set nodigest flag, if required
  ansible.builtin.set_fact:
    signed_package: false
  when:
    - "sentinelone_client_rpm_version.stdout is version('23.3.2.12', '<')"
