---
- name: Execute Modules and Roles
  hosts: all
  gather_facts: true

  vars_files:
    - ../vars/test_vars.yml

  tasks:
    - name: "Block: Converge Create site and get registration token from API"
      run_once: true
      delegate_to: localhost
      block:
        - name: "Converge: Create a site"
          sva.sentinelone.sentinelone_sites:
            console_url: "{{ console_url }}"
            token: "{{ api_token }}"
            name: "{{ site }}"
            license_type: "{{ license_type }}"
            total_agents: "{{ total_agents }}"
            site_type: "{{ site_type }}"

        - name: "Converge: Get site from API"
          ansible.builtin.uri:
            url: "{{ console_url }}/web/api/v2.1/sites?name={{ site }}&state=active"
            method: GET
            return_content: true
            headers:
              Accept: application/json
              Authorization: "APIToken {{ api_token }}"
            validate_certs: true
            status_code: 200
          register: get_site_result
          no_log: "{{ hide_sensitive | default(true) }}"
          until: get_site_result.status == 200
          retries: 3
          delay: 20

        - name: "Set site_id"
          ansible.builtin.set_fact:
            site_id: "{{ get_site_result.json.data.sites[0].id }}"

        - name: "Get registration token"
          ansible.builtin.uri:
            url: "{{ console_url }}/web/api/v2.1/sites/{{ site_id }}/token"
            method: GET
            return_content: true
            headers:
              Accept: application/json
              Authorization: "APIToken {{ api_token }}"
            validate_certs: true
            status_code: 200
          register: get_reg_token_result
          delegate_to: localhost
          no_log: "{{ hide_sensitive | default(true) }}"
          until: get_reg_token_result.status == 200
          retries: 3
          delay: 20

    - name: "Converge: Install custom agent"
      ansible.builtin.include_role:
        name: sva.sentinelone.install_agent
      vars:
        check_console_retries: 18
        check_console_retry_delay: 20
        custom_client_url: "{{ client_url }}"
        registration_token: "{{ get_reg_token_result.json.data.token }}"

    # Extra wait bc my testmachine is slow bc it has to emulate x86_64 (arm based)
    # - name: "Pause for 8 minutes to wait for s1 agent to become ready"
    #   ansible.builtin.pause:
    #     minutes: 8
